import { Player, Match, Tournament } from "./types";

export const players: Player[] = [
  {
    id: "p1",
    name: "Ines Adeyemi",
    rank: "A",
    league: "One Alphabet League",
    judgedMatches: 34,
    wins: 41,
    losses: 6,
    joinedAt: "2025-02-11",
    country: "Nigeria",
    bio: "Reigning Ace. Known for reframing economic debates around lived experience rather than statistics.",
  },
  {
    id: "p2",
    name: "Kenji Watanabe",
    rank: "B",
    league: "One Alphabet League",
    judgedMatches: 22,
    wins: 37,
    losses: 9,
    joinedAt: "2025-01-30",
    country: "Japan",
  },
  {
    id: "p3",
    name: "Priya Menon",
    rank: "C",
    league: "One Alphabet League",
    judgedMatches: 18,
    wins: 29,
    losses: 11,
    joinedAt: "2025-03-02",
    country: "India",
  },
  {
    id: "p4",
    name: "Lucas Ferreira",
    rank: "D",
    league: "One Alphabet League",
    judgedMatches: 15,
    wins: 25,
    losses: 10,
    joinedAt: "2025-03-14",
    country: "Brazil",
  },
  {
    id: "p5",
    name: "Sara Haddad",
    rank: "AA",
    league: "Two Alphabet League",
    judgedMatches: 11,
    wins: 20,
    losses: 8,
    joinedAt: "2025-04-01",
    country: "Jordan",
  },
  {
    id: "p6",
    name: "Marcus Webb",
    rank: "AB",
    league: "Two Alphabet League",
    judgedMatches: 9,
    wins: 18,
    losses: 9,
    joinedAt: "2025-04-05",
    country: "United Kingdom",
  },
  {
    id: "p7",
    name: "Anya Sokolova",
    rank: "AC",
    league: "Two Alphabet League",
    judgedMatches: 7,
    wins: 15,
    losses: 10,
    joinedAt: "2025-04-20",
    country: "Poland",
  },
  {
    id: "p8",
    name: "Diego Ramirez",
    rank: "BA",
    league: "Alphabet League",
    judgedMatches: 2,
    wins: 6,
    losses: 4,
    joinedAt: "2025-06-01",
    country: "Mexico",
  },
];

export const matches: Match[] = [
  {
    id: "m1",
    topic: "Should AI systems be allowed to judge human debates?",
    playerAId: "p1",
    playerBId: "p2",
    judgeId: "p3",
    refereeId: "p4",
    tournament: "Twilight Race to Get the Ace",
    league: "One Alphabet League",
    winnerId: "p1",
    date: "2026-01-18",
    tags: ["AI regulation", "epistemics", "judging"],
    aiSummary:
      "Adeyemi argued that an AI judge removes a specific kind of bias but introduces an opacity problem judges can't be cross-examined on. Watanabe countered that human judges are already opaque in practice. The match turned on Adeyemi's closing reframe: opacity you can appeal is different from opacity you can't.",
    videoUrl: "#",
    transcriptUrl: "#",
  },
  {
    id: "m2",
    topic: "Is a ceasefire that both sides call a win actually peace?",
    playerAId: "p5",
    playerBId: "p6",
    judgeId: "p1",
    refereeId: "p2",
    tournament: "Emergency League: America\u2013Iran",
    league: "Two Alphabet League",
    winnerId: "p6",
    date: "2026-02-03",
    tags: ["geopolitics", "conflict", "emergency league"],
    aiSummary:
      "Haddad framed dual-claimed victory as a rhetorical device that delays reckoning. Webb argued ambiguity is often the only politically viable path to de-escalation, and that demanding a clear loser prolongs conflict rather than shortening it.",
    videoUrl: "#",
    transcriptUrl: "#",
  },
  {
    id: "m3",
    topic: "Should Mars colonists be allowed to renounce Earth citizenship?",
    playerAId: "p7",
    playerBId: "p5",
    judgeId: "p6",
    refereeId: "p1",
    tournament: "Emergency League: Mars Landing",
    league: "Two Alphabet League",
    winnerId: "p7",
    date: "2026-03-22",
    tags: ["space", "citizenship", "emergency league"],
    aiSummary:
      "Sokolova argued that citizenship tied to a planet you can't return to is coercion dressed as belonging. Haddad pushed back that no colony survives its first decade without a guaranteeing power. Judges scored it for the sharper first-principles framing.",
    videoUrl: "#",
    transcriptUrl: "#",
  },
  {
    id: "m4",
    topic: "Does procrastination protect us from a truth we're not ready for?",
    playerAId: "p3",
    playerBId: "p4",
    judgeId: "p2",
    refereeId: "p5",
    tournament: "The Unknown Road to One Alphabet",
    league: "Two Alphabet League",
    winnerId: "p3",
    date: "2026-04-09",
    tags: ["psychology", "procrastination", "promotion"],
    aiSummary:
      "Menon argued procrastination is often a correctly-calibrated fear response, not a discipline failure. Ferreira maintained that framing lets people off the hook too easily. The judge cited Menon's distinction between avoidance-of-failure and avoidance-of-finding-out as the deciding move.",
    videoUrl: "#",
    transcriptUrl: "#",
  },
  {
    id: "m5",
    topic: "Is climate anxiety a rational response or a learned helplessness?",
    playerAId: "p8",
    playerBId: "p7",
    judgeId: "p3",
    refereeId: "p6",
    tournament: "Emergency League: Climate",
    league: "Alphabet League",
    winnerId: null,
    date: "2026-05-30",
    tags: ["climate", "psychology", "emergency league"],
    aiSummary:
      "A close, undecided match. Ramirez treated climate anxiety as evidence of accurate risk perception; Sokolova argued it's often untethered from any action the person actually takes, which she called the tell of learned helplessness rather than rational fear.",
    videoUrl: "#",
    transcriptUrl: "#",
  },
];

export const tournaments: Tournament[] = [
  {
    id: "t1",
    name: "The Unknown Road to One Alphabet",
    type: "promotion",
    league: "Two Alphabet League",
    status: "active",
    dates: "Rolling \u2014 online",
    description:
      "Two Alphabet players challenge One Alphabet players for promotion into the elite league. Currently held online; physical qualification arrives once infrastructure allows it.",
  },
  {
    id: "t2",
    name: "Twilight Race to Get the Ace",
    type: "flagship",
    league: "One Alphabet League",
    status: "upcoming",
    dates: "January 2027",
    description:
      "One Alphabet League only. Players defend their standing and race to become A, the single highest-ranked player in the sport.",
  },
  {
    id: "t3",
    name: "Emergency League: AI Regulation",
    type: "emergency",
    league: "Cross-League",
    status: "active",
    dates: "Opened July 2026",
    description:
      "A temporary league activated to hold high-quality debate on the unfolding AI regulation landscape while it's still being written.",
  },
  {
    id: "t4",
    name: "Emergency League: America\u2013Iran",
    type: "emergency",
    league: "Cross-League",
    status: "completed",
    dates: "Closed February 2026",
    description:
      "Archived. Debates from this league remain searchable and form part of the permanent record.",
  },
];

export function getPlayer(id: string): Player | undefined {
  return players.find((p) => p.id === id);
}
